name: 'Test PR'
on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    name: 'Run tests'
    runs-on: ubuntu-latest
    steps:
      - name: 'Check out code'
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: 'Set up Java 17'
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: 'Install Maven'
        run: sudo apt-get update && sudo apt-get install --yes maven

      - name: 'Check code is formatted correctly'
        run: mvn spotless:check --batch-mode -U

      - name: 'Run tests'
        run: mvn verify --batch-mode -U
